"""initial schema

Revision ID: d81dfc442a33
Revises:
Create Date: 2026-10-09 18:49:16.531672

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d81dfc442a33"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_results",
        sa.Column("analysis", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("analysis", "subject", name=op.f("pk_analysis_results")),
    )
    op.create_table(
        "items",
        sa.Column("item_nbr", sa.Integer(), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("item_class", sa.SmallInteger(), nullable=False),
        sa.Column("perishable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("item_nbr", name=op.f("pk_items")),
    )
    op.create_index(op.f("ix_items_family"), "items", ["family"], unique=False)
    op.create_table(
        "model_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("train_start", sa.Date(), nullable=False),
        sa.Column("train_end", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_runs")),
    )
    op.create_table(
        "quality_checks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("check_name", sa.String(length=64), nullable=False),
        sa.Column("table_name", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("violations", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_checks")),
    )
    op.create_index(
        op.f("ix_quality_checks_checked_at"), "quality_checks", ["checked_at"], unique=False
    )
    op.create_table(
        "stores",
        sa.Column("store_nbr", sa.SmallInteger(), nullable=False),
        sa.Column("city", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("store_type", sa.String(length=4), nullable=False),
        sa.Column("cluster", sa.SmallInteger(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("store_nbr", name=op.f("pk_stores")),
    )
    op.create_table(
        "backtest_scores",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("cutoff", sa.Date(), nullable=False),
        sa.Column("horizon", sa.SmallInteger(), nullable=False),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["model_runs.id"],
            name=op.f("fk_backtest_scores_run_id_model_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "cutoff", "horizon", "metric", name=op.f("pk_backtest_scores")
        ),
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("forecast_origin", sa.Date(), nullable=False),
        sa.Column("item_run_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_run_id"], ["model_runs.id"], name=op.f("fk_releases_item_run_id_model_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
    )
    op.create_index(
        "uq_releases_current",
        "releases",
        ["is_current"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    op.create_table(
        "family_forecasts",
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("store_nbr", sa.SmallInteger(), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("p10", sa.Double(), nullable=True),
        sa.Column("p50", sa.Double(), nullable=False),
        sa.Column("p90", sa.Double(), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_family_forecasts_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "release_id",
            "store_nbr",
            "family",
            "model_name",
            "target_date",
            name=op.f("pk_family_forecasts"),
        ),
    )
    op.create_table(
        "family_sales_history",
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("store_nbr", sa.SmallInteger(), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("unit_sales", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_family_sales_history_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "store_nbr", "family", "sale_date", name=op.f("pk_family_sales_history")
        ),
    )
    op.create_table(
        "item_forecasts",
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("store_nbr", sa.SmallInteger(), nullable=False),
        sa.Column("item_nbr", sa.Integer(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("p10", sa.Double(), nullable=False),
        sa.Column("p50", sa.Double(), nullable=False),
        sa.Column("p90", sa.Double(), nullable=False),
        sa.Column("onpromotion", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_item_forecasts_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "store_nbr", "item_nbr", "target_date", name=op.f("pk_item_forecasts")
        ),
    )
    op.create_table(
        "order_plans",
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("store_nbr", sa.SmallInteger(), nullable=False),
        sa.Column("item_nbr", sa.Integer(), nullable=False),
        sa.Column("cover_days", sa.SmallInteger(), nullable=False),
        sa.Column("service_level", sa.Double(), nullable=False),
        sa.Column("expected_demand", sa.Double(), nullable=False),
        sa.Column("order_quantity", sa.Double(), nullable=False),
        sa.Column("safety_stock", sa.Double(), nullable=False),
        sa.Column("expected_lost_units", sa.Double(), nullable=False),
        sa.Column("expected_leftover_units", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_order_plans_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("release_id", "store_nbr", "item_nbr", name=op.f("pk_order_plans")),
    )
    op.create_table(
        "policy_evaluations",
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("policy", sa.String(length=32), nullable=False),
        sa.Column("segment", sa.String(length=64), nullable=False),
        sa.Column("demand_units", sa.Double(), nullable=False),
        sa.Column("lost_units", sa.Double(), nullable=False),
        sa.Column("leftover_units", sa.Double(), nullable=False),
        sa.Column("fill_rate", sa.Double(), nullable=False),
        sa.Column("total_cost", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_policy_evaluations_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "policy", "segment", name=op.f("pk_policy_evaluations")
        ),
    )
    op.create_table(
        "sales_history",
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("store_nbr", sa.SmallInteger(), nullable=False),
        sa.Column("item_nbr", sa.Integer(), nullable=False),
        sa.Column("sale_date", sa.Date(), nullable=False),
        sa.Column("unit_sales", sa.Double(), nullable=False),
        sa.Column("onpromotion", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_sales_history_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "store_nbr", "item_nbr", "sale_date", name=op.f("pk_sales_history")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sales_history")
    op.drop_table("policy_evaluations")
    op.drop_table("order_plans")
    op.drop_table("item_forecasts")
    op.drop_table("family_sales_history")
    op.drop_table("family_forecasts")
    op.drop_index(
        "uq_releases_current", table_name="releases", postgresql_where=sa.text("is_current")
    )
    op.drop_table("releases")
    op.drop_table("backtest_scores")
    op.drop_table("stores")
    op.drop_index(op.f("ix_quality_checks_checked_at"), table_name="quality_checks")
    op.drop_table("quality_checks")
    op.drop_table("model_runs")
    op.drop_index(op.f("ix_items_family"), table_name="items")
    op.drop_table("items")
    op.drop_table("analysis_results")
    # ### end Alembic commands ###
